apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: minio-scale-out
spec:
  # Specifies the name of the Cluster resource that this operation is targeting.
  clusterName: minio-cluster
  type: HorizontalScaling
  # Lists HorizontalScaling objects, each specifying scaling requirements for a Component, including desired total replica counts, configurations for new instances, modifications for existing instances, and instance downscaling options
  horizontalScaling:
    # Specifies the name of the Component.
  - componentName: minio
    # Specifies the replica changes for scaling in components
    scaleOut:
      # Specifies the replica changes for the component.
      # add one more replica to current component
      replicaChanges: 2
