apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: minio-start
spec:
  # Specifies the name of the Cluster resource that this operation is targeting.
  clusterName: minio-cluster
  type: Start
