apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: minio-verticalscaling
spec:
  # Specifies the name of the Cluster resource that this operation is targeting.
  clusterName: minio-cluster
  type: VerticalScaling
  # Lists VerticalScaling objects, each specifying a component and its desired compute resources for vertical scaling.
  verticalScaling:
  - componentName: minio
    # VerticalScaling refers to the process of adjusting the compute resources (e.g., CPU, memory) allocated to a Component. It defines the parameters required for the operation.
    requests:
      cpu: '1'
      memory: 1Gi
    limits:
      cpu: '1'
      memory: 1Gi
