# dns 自动安装，可选"coredns"和“kubedns”
dns_install: "yes"
dns_backend: "coredns"

# metric server 自动安装
metricsserver_install: "yes"

# dashboard 自动安装
dashboard_install: "yes"

# ingress 自动安装
ingress_install: "no"
ingress_backend: "traefik"

# heapster 自动安装
heapster_install: "no"

# efk 自动安装
efk_install: "no"

# prometheus 自动安装
prometheus_install: "no"
