# 离线安装基础系统包
- name: 准备离线安装包目录
  file: name=/opt/kube/packages/basic state=directory

- block:
  - name: 分发 basic_xenial 离线包
    copy:
      src: "{{ base_dir }}/down/packages/basic_xenial.tar.gz"
      dest: "/opt/kube/packages/basic/basic_xenial.tar.gz"

  - name: 安装 basic_xenial 离线包
    shell: 'cd /opt/kube/packages/basic && tar zxf basic_xenial.tar.gz && \
           dpkg -i *.deb > /tmp/install_basic.log 2>&1'
  when: ansible_distribution_release == "xenial"

- block:
  - name: 分发 basic_centos7 离线包
    copy:
      src: "{{ base_dir }}/down/packages/basic_centos7.tar.gz"
      dest: "/opt/kube/packages/basic/basic_centos7.tar.gz"

  - name: 安装 basic_centos7 离线包
    shell: 'cd /opt/kube/packages/basic && tar zxf basic_centos7.tar.gz && \
           basic -Uvh --nodeps *.rpm > /tmp/install_basic.log 2>&1'
  when:
  - 'ansible_distribution == "CentOS"'
  - 'ansible_distribution_major_version == "7"'
