apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mysql-cluster-pod-monitor
  namespace: monitor    # Note: this is namespace for prometheus operator
  labels:               # this is labels set in 'prometheus.spec.podMonitorSelector'
    release: prometheus
spec:
  jobLabel: app.kubernetes.io/managed-by
  # defines the labels which are transferred from the
  # associated Kubernetes 'Pod' object onto the ingested metrics
  # set the lables w.r.t you own needs
  podTargetLabels:
  - app.kubernetes.io/instance
  - app.kubernetes.io/managed-by
  - apps.kubeblocks.io/component-name
  - apps.kubeblocks.io/pod-name
  podMetricsEndpoints:
    - path: /metrics
      port: http-metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app.kubernetes.io/instance: semisync-mysql-cluster
      apps.kubeblocks.io/component-name: mysql

