# 部分cilium相关配置, Note: cilium 需要Linux kernel >= 4.9.17

# debug mode
Debug_Mode: "false"

# Removes any Cilium state, e.g. BPF policy maps, before starting
Clean_Start: "false"

# If true, the policy with the entity 'reserved:host' allows traffic from 'world'
Legacy_Host_Policy: "true"

# 镜像版本
busybox_ver: "1.28.4"
cilium_ver: "v1.1.2"

# 离线镜像tar包
cilium_offline: "cilium_{{ cilium_ver }}.tar"
busybox_offline: "busybox_{{ busybox_ver }}.tar"
