# 部分cilium相关配置, Note: cilium 需要Linux kernel >= 4.9.17

# 如果 node 节点有多块网卡，请设置 true
# 另外发现设置为 true 时能够解决v1.10使用ipvs偶尔出现pod内‘dial tcp 10.68.0.1:443: i/o timeout’的 bug
NODE_WITH_MULTIPLE_NETWORKS: "true"

# debug mode
Debug_Mode: "false"

# Removes any Cilium state, e.g. BPF policy maps, before starting
Clean_Start: "false"

# If true, the policy with the entity 'reserved:host' allows traffic from 'world'
Legacy_Host_Policy: "true"

# 镜像版本
busybox_ver: "1.28.4"
cilium_ver: "v1.1.4"

# 离线镜像tar包
cilium_offline: "cilium_{{ cilium_ver }}.tar"
busybox_offline: "busybox_{{ busybox_ver }}.tar"

# 识别操作系统，加载对应的Pause容器离线镜像tar包
OS_VER: "{{ ansible_distribution }}"
for_redhat_pod: "rhel7-pod-infrastructure.tar"
for_other_pod: "pause_3.1.tar"
pause_offline: "{%- if OS_VER == 'RedHat' -%} \
                {{ for_redhat_pod }} \
              {%- else -%} \
                {{ for_other_pod }} \
              {%- endif -%}"