# 设置 dns svc ip (这里选用 SERVICE_CIDR 中第2个IP)
CLUSTER_DNS_SVC_IP: "{{ SERVICE_CIDR | ipaddr('net') | ipaddr(2) | ipaddr('address') }}"

#
coredns_offline: "coredns_{{ corednsVer }}.tar"

metricsserver_offline: "metrics-server_{{ metricsVer }}.tar"

dashboard_offline: "dashboard_{{ dashboardVer }}.tar"

metricsscraper_offline: "metrics-scraper_{{ dashboardMetricsScraperVer }}.tar"


# metallb 自动安装
#metallb_install: "no"
#metallbVer: "v0.7.3"
# 模式选择: 二层 "layer2" 或者三层 "bgp"
#metallb_protocol: "layer2"
#metallb_offline: "metallb_{{ metallbVer }}.tar"
#metallb_vip_pool: "192.168.1.240/29"
