- block:
    - name: 准备dnscache的部署文件
      template: src=dns/nodelocaldns-ipvs.yaml.j2 dest={{ cluster_dir }}/yml/nodelocaldns.yaml
      when: "PROXY_MODE == 'ipvs'"

    - name: 准备dnscache的部署文件
      template: src=dns/nodelocaldns-iptables.yaml.j2 dest={{ cluster_dir }}/yml/nodelocaldns.yaml
      when: "PROXY_MODE == 'iptables'"

    - name: 创建dnscache部署
      shell: "{{ base_dir }}/bin/kubectl apply -f {{ cluster_dir }}/yml/nodelocaldns.yaml"
  when: 'ENABLE_LOCAL_DNS_CACHE|bool'
