---
galaxy_info:
  author: "Sebastian Gumprich"
  description: 'This Ansible role provides numerous security-related configurations, providing all-round base protection.'
  company: Hardening Framework Team
  license: Apache License 2.0
  min_ansible_version: '2.4.2'
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
    - name: Amazon
  galaxy_tags:
    - system
    - security
    - hardening
dependencies: []
