apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: clickhouse-pod-monitor
  namespace: monitor    # prometheus namespace
  labels:               # this is labels set in `prometheus.spec.podMonitorSelector`
    release: prometheus
spec:
  jobLabel: app.kubernetes.io/managed-by
  # defines the labels which are transferred from the
  # associated Kubernetes `Pod` object onto the ingested metrics
  # set the lables w.r.t you own needs
  podTargetLabels:
  - app.kubernetes.io/instance
  - app.kubernetes.io/managed-by
  - apps.kubeblocks.io/component-name
  - apps.kubeblocks.io/pod-name
  podMetricsEndpoints:
    - path: /metrics
      port: http-metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - default 
  selector:
    matchLabels:
      app.kubernetes.io/instance: clickhouse-cluster # set cluster name
      apps.kubeblocks.io/component-name: clickhouse
