# to clean 'etcd' nodes
- hosts:
  - etcd
  - new-etcd
  tasks:
  - name: stop and disable etcd service
    service:
      name: etcd
      state: stopped
      enabled: no
    ignore_errors: true

  - name: remove files and dirs
    file: name={{ item }} state=absent
    with_items:
    - "/var/lib/etcd"
    - "/etc/etcd/"
    - "/backup/k8s"
    - "/etc/systemd/system/etcd.service"
