- name: 准备containerd相关目录
  file: name={{ item }} state=directory
  with_items:
  - "{{ bin_dir }}/containerd-bin"
  - "{{ CONTAINERD_CONFIG_DIR }}/certs.d/docker.io"
  - "{{ CONTAINERD_CONFIG_DIR }}/certs.d/easzlab.io.local:5000"
  - "{{ CONTAINERD_CONFIG_DIR }}/certs.d/{{ HARBOR_REGISTRY }}"
  tags: support_private_registry

- name: 准备INSECURE REGISTRY 目录
  file:
    path: "{{ CONTAINERD_CONFIG_DIR }}/certs.d/{{ item.split('/')[2] }}"
    state: directory
  loop: "{{ INSECURE_REG }}"

- name: 加载内核模块 overlay
  modprobe: name=overlay state=present

- name: 下载 containerd 二进制文件
  copy: src={{ item }} dest={{ bin_dir }}/containerd-bin/ mode=0755
  with_fileglob:
  - "{{ base_dir }}/bin/containerd-bin/*"
  tags: upgrade

- name: 下载 crictl
  copy: src={{ base_dir }}/bin/crictl dest={{ bin_dir }}/crictl mode=0755

- name: 创建 containerd 配置文件
  template: src=config.toml.j2 dest={{ CONTAINERD_CONFIG_DIR }}/config.toml
  tags: upgrade

- name: 配置docker.io 加速镜像
  template: src=docker.io/hosts.toml.j2 dest={{ CONTAINERD_CONFIG_DIR }}/certs.d/docker.io/hosts.toml

- name: 配置信任 INSECURE REGISTRY 仓库
  template:
    src: hosts.toml.j2
    dest: "{{ CONTAINERD_CONFIG_DIR }}/certs.d/{{ item.split('/')[2] }}/hosts.toml"
  loop: "{{ INSECURE_REG }}"

- name: 配置信任 {{ HARBOR_REGISTRY }} 仓库
  template: src="HARBOR_REGISTRY/hosts.toml.j2" dest={{ CONTAINERD_CONFIG_DIR }}/certs.d/{{ HARBOR_REGISTRY }}/hosts.toml
  tags: support_private_registry

- name: 创建systemd unit文件
  template: src=containerd.service.j2 dest=/etc/systemd/system/{{ CONTAINERD_SERVICE_NAME }}
  tags: upgrade

- name: 创建 crictl 配置
  template: src=crictl.yaml.j2 dest=/etc/crictl.yaml

- name: 开机启用 containerd 服务
  shell: 'systemctl enable {{ CONTAINERD_SERVICE_NAME }}'
  ignore_errors: true

- name: 开启 containerd 服务
  shell: 'systemctl daemon-reload && systemctl restart {{ CONTAINERD_SERVICE_NAME }}'
  tags: upgrade

- name: 轮询等待containerd服务运行
  shell: "systemctl is-active {{ CONTAINERD_SERVICE_NAME }}"
  register: containerd_status
  until: '"active" in containerd_status.stdout'
  retries: 8
  delay: 2
  tags: upgrade
