- name: 准备containerd相关目录
  file: name={{ item }} state=directory
  with_items:
  - "{{ bin_dir }}"
  - "/etc/containerd"

- name: 安装 libseccomp2
  package: name=libseccomp2 state=present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  
- name: 安装 libseccomp
  package: name=libseccomp state=present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Amazon"

- name: 加载内核模块 overlay
  modprobe: name=overlay state=present

- name: 下载 containerd 二进制文件
  copy: src={{ base_dir }}/bin/containerd-bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - containerd
  - containerd-shim
  - containerd-shim-runc-v1
  - containerd-stress
  - crictl
  - critest
  - ctr
  - runc
  tags: upgrade

- name: 创建 containerd 配置文件
  template: src=config.toml.j2 dest=/etc/containerd/config.toml
  tags: upgrade

- name: 创建systemd unit文件
  template: src=containerd.service.j2 dest=/etc/systemd/system/containerd.service
  tags: upgrade

- name: 创建 crictl 配置
  template: src=crictl.yaml.j2 dest=/etc/crictl.yaml

- name: 开机启用 containerd 服务
  shell: systemctl enable containerd
  ignore_errors: true

- name: 开启 containerd 服务
  shell: systemctl daemon-reload && systemctl restart containerd
  tags: upgrade

- name: 轮询等待containerd服务运行
  shell: "systemctl status containerd.service|grep Active"
  register: containerd_status
  until: '"running" in containerd_status.stdout'
  retries: 8
  delay: 2
  tags: upgrade
